# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaae56d02d5bddadf8bac6aabb7cf432d1349151da9c515f42eeb13659cef1fc3c964e045293b524353bed75a7c4cd887033a9fbf604f03acb2a62e61ddbd080

test:
  secret_key_base: 7638953f4a30c9d331121e37b9246d84a60d01c527ae90ed4d0a2d79ee0bba90fda3809944e0b502aa598836e43e101fa1f0880c092c6fa1b9499760c4791ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
