# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54a6d8a8f9e94ba18b306b89c300b70218aa499c5b80c508fbd3cdb488ca8397e001892194fba49399e65ea38300e95b9b9f2be55387d560d8b3b4568c963830

test:
  secret_key_base: ed58b0344f61f1abf8ba05e3c43939d953af35b6917357bbe6cddc7440eab06e33866f5d8a7aeebc2e79e681fdf24b439201428b0a157456ec754ad4b9b58874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
